//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_1_Default.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LR_1_Default.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название приложения:.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPF MVVM Демо - Типы привязок.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка флажка.
        /// </summary>
        internal static string CheckBoxBinding {
            get {
                return ResourceManager.GetString("CheckBoxBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение счетчика хранится в ViewModel и отображается с однонаправленной привязкой.
        /// </summary>
        internal static string CounterDescription {
            get {
                return ResourceManager.GetString("CounterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример счетчика.
        /// </summary>
        internal static string CounterExample {
            get {
                return ResourceManager.GetString("CounterExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Триггеры.
        /// </summary>
        internal static string DataTriggers {
            get {
                return ResourceManager.GetString("DataTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data триггеры реагируют на изменения значений в ViewModel..
        /// </summary>
        internal static string DataTriggersDescription {
            get {
                return ResourceManager.GetString("DataTriggersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        internal static string DefaultBinding {
            get {
                return ResourceManager.GetString("DefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию в WPF - это TwoWay для редактируемых элементов управления (TextBox, CheckBox и т.д.) и OneWay для элементов только для чтения. Обновление источника происходит при потере фокуса для TextBox..
        /// </summary>
        internal static string DefaultBindingDescription {
            get {
                return ResourceManager.GetString("DefaultBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация привязки по умолчанию.
        /// </summary>
        internal static string DefaultBindingTitle {
            get {
                return ResourceManager.GetString("DefaultBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка к свойству ViewModel.
        /// </summary>
        internal static string DirectBindingToViewModel {
            get {
                return ResourceManager.GetString("DirectBindingToViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображаемый текст (привязан к тому же свойству):.
        /// </summary>
        internal static string DisplayedText {
            get {
                return ResourceManager.GetString("DisplayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это демонстрирует прямую привязку элемент-к-элементу без использования ViewModel.
        /// </summary>
        internal static string ElementToElementBindingDescription {
            get {
                return ResourceManager.GetString("ElementToElementBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример привязки элемент-к-элементу.
        /// </summary>
        internal static string ElementToElementBindingExample {
            get {
                return ResourceManager.GetString("ElementToElementBindingExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить функцию.
        /// </summary>
        internal static string EnableFeature {
            get {
                return ResourceManager.GetString("EnableFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Триггеры.
        /// </summary>
        internal static string EventTriggers {
            get {
                return ResourceManager.GetString("EventTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event триггеры реагируют на события мыши, такие как наведение и выбор..
        /// </summary>
        internal static string EventTriggersDescription {
            get {
                return ResourceManager.GetString("EventTriggersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наведите курсор на элементы для отображения триггера MouseOver, нажмите для отображения триггера выбора.
        /// </summary>
        internal static string EventTriggersNote {
            get {
                return ResourceManager.GetString("EventTriggersNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя:.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите текст в поля выше - полное имя обновляется автоматически!.
        /// </summary>
        internal static string FullNameAutoUpdate {
            get {
                return ResourceManager.GetString("FullNameAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык интерфейса изменен.
        /// </summary>
        internal static string LanguageChangedMessage {
            get {
                return ResourceManager.GetString("LanguageChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка:.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время загрузки:.
        /// </summary>
        internal static string LoadTime {
            get {
                return ResourceManager.GetString("LoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MultiDataTrigger.
        /// </summary>
        internal static string MultiDataTrigger {
            get {
                return ResourceManager.GetString("MultiDataTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия: пусто (красный), 1-2 символа (оранжевый), 3-20 символов (зеленый), &gt;20 символов (красный).
        /// </summary>
        internal static string MultiDataTriggerConditions {
            get {
                return ResourceManager.GetString("MultiDataTriggerConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MultiDataTrigger применяет стили, когда выполняются несколько условий одновременно..
        /// </summary>
        internal static string MultiDataTriggerDescription {
            get {
                return ResourceManager.GetString("MultiDataTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однократная привязка.
        /// </summary>
        internal static string OneTimeBinding {
            get {
                return ResourceManager.GetString("OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однократная привязка устанавливает свойство цели один раз из источника при инициализации. Последующие изменения источника НЕ влияют на цель. Идеально подходит для статического контента, такого как заголовки, метки и данные конфигурации..
        /// </summary>
        internal static string OneTimeBindingDescription {
            get {
                return ResourceManager.GetString("OneTimeBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Примечание: Этот контент был установлен один раз при запуске приложения и не может быть изменен динамически..
        /// </summary>
        internal static string OneTimeBindingNote {
            get {
                return ResourceManager.GetString("OneTimeBindingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация однократной привязки.
        /// </summary>
        internal static string OneTimeBindingTitle {
            get {
                return ResourceManager.GetString("OneTimeBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однонаправленная привязка.
        /// </summary>
        internal static string OneWayBinding {
            get {
                return ResourceManager.GetString("OneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однонаправленная привязка обновляет цель при изменении источника, но изменения цели НЕ обновляют источник. Полезно для отображения производных данных, доступных только для чтения..
        /// </summary>
        internal static string OneWayBindingDescription {
            get {
                return ResourceManager.GetString("OneWayBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация однонаправленной привязки.
        /// </summary>
        internal static string OneWayBindingTitle {
            get {
                return ResourceManager.GetString("OneWayBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработанный вывод (только для чтения - однонаправленная привязка).
        /// </summary>
        internal static string ProcessedOutputReadOnly {
            get {
                return ResourceManager.GetString("ProcessedOutputReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработанный текст формируется из источника и обновляется автоматически, но не может быть отредактирован напрямую..
        /// </summary>
        internal static string ProcessedTextDescription {
            get {
                return ResourceManager.GetString("ProcessedTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property Триггеры.
        /// </summary>
        internal static string PropertyTriggers {
            get {
                return ResourceManager.GetString("PropertyTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property триггеры применяют стили, когда свойство элемента управления достигает определенного значения..
        /// </summary>
        internal static string PropertyTriggersDescription {
            get {
                return ResourceManager.GetString("PropertyTriggersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать текст.
        /// </summary>
        internal static string ShowText {
            get {
                return ResourceManager.GetString("ShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка ползунка.
        /// </summary>
        internal static string SliderBinding {
            get {
                return ResourceManager.GetString("SliderBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример ползунка.
        /// </summary>
        internal static string SliderExample {
            get {
                return ResourceManager.GetString("SliderExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ползунок с привязкой по умолчанию.
        /// </summary>
        internal static string SliderWithDefaultBinding {
            get {
                return ResourceManager.GetString("SliderWithDefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения источника влияют на отображение ниже:.
        /// </summary>
        internal static string SourceChangesAffectDisplay {
            get {
                return ResourceManager.GetString("SourceChangesAffectDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходные данные (редактируемые).
        /// </summary>
        internal static string SourceDataEditable {
            get {
                return ResourceManager.GetString("SourceDataEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный TextBox:.
        /// </summary>
        internal static string SourceTextBox {
            get {
                return ResourceManager.GetString("SourceTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статическая информация (устанавливается один раз при загрузке).
        /// </summary>
        internal static string StaticInformation {
            get {
                return ResourceManager.GetString("StaticInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Целевой TextBlock (привязан к исходному TextBox):.
        /// </summary>
        internal static string TargetTextBlock {
            get {
                return ResourceManager.GetString("TargetTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox с привязкой по умолчанию:.
        /// </summary>
        internal static string TextBoxWithDefaultBinding {
            get {
                return ResourceManager.GetString("TextBoxWithDefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот текст виден, когда флажок установлен.
        /// </summary>
        internal static string TextVisibleWhenChecked {
            get {
                return ResourceManager.GetString("TextVisibleWhenChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Triggers {
            get {
                return ResourceManager.GetString("Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация триггеров.
        /// </summary>
        internal static string TriggersDemo {
            get {
                return ResourceManager.GetString("TriggersDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        internal static string TwoWayBinding {
            get {
                return ResourceManager.GetString("TwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка синхронизирует источник и цель. Изменения в интерфейсе обновляют ViewModel, а изменения в ViewModel автоматически обновляют интерфейс..
        /// </summary>
        internal static string TwoWayBindingDescription {
            get {
                return ResourceManager.GetString("TwoWayBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация двухсторонней привязки.
        /// </summary>
        internal static string TwoWayBindingTitle {
            get {
                return ResourceManager.GetString("TwoWayBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о пользователе.
        /// </summary>
        internal static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение обновляется при потере фокуса.
        /// </summary>
        internal static string ValueUpdatesOnLostFocus {
            get {
                return ResourceManager.GetString("ValueUpdatesOnLostFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приветственное сообщение:.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что такое привязка по умолчанию?.
        /// </summary>
        internal static string WhatIsDefaultBinding {
            get {
                return ResourceManager.GetString("WhatIsDefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что такое однократная привязка?.
        /// </summary>
        internal static string WhatIsOneTimeBinding {
            get {
                return ResourceManager.GetString("WhatIsOneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что такое однонаправленная привязка?.
        /// </summary>
        internal static string WhatIsOneWayBinding {
            get {
                return ResourceManager.GetString("WhatIsOneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что такое двухсторонняя привязка?.
        /// </summary>
        internal static string WhatIsTwoWayBinding {
            get {
                return ResourceManager.GetString("WhatIsTwoWayBinding", resourceCulture);
            }
        }
    }
}
